Repository MTVS-Noblesse/Triplay-frontend, pull requests merged in 2024-09, with the labels that each got.

#18 Feat: 로그인 기능 구현 완료
  certs/triplay.crt
  certs/triplay.key
  src/App.jsx
  src/api/oauth.js
  src/auth/CallBack.jsx
  src/axios/AxiosInstance.js
  src/main.jsx
  src/pages/User/Login.jsx
  src/redux/Auth/AuthActions.js
  src/redux/Auth/AuthReducer.js
  src/redux/Store.jsx
  src/redux/example/ExampleActions.js
  src/redux/example/ExampleReducer.js
  src/redux/example/Store.jsx
  vite.config.js
Labels: ✨Feature

#17 Refactor: Domain(Plan) - planImageFile redux
  src/App.jsx
  src/pages/Plan/MobileClipReady.jsx
  src/redux/Plan/PlanImageActions.js
  src/redux/Plan/PlanImageReducer.js
  src/redux/Store.jsx
Labels: ✨Feature

#22 Fix: 로그인 오류 수정
  src/api/oauth.js
  src/auth/CallBack.jsx
  src/axios/AxiosInstance.js
  src/main.jsx
  src/pages/User/Login.jsx
Labels: 🐞Fix

#24 Refactor: Header hover 효과 해제, Post 구조 수정
  src/layout/Header.jsx
  src/pages/Post/Post.jsx
Labels: 🔨 Refactor

#28 Feat: 리프레시 토큰 구현완료
  src/App.jsx
  src/api/oauth.js
  src/auth/CallBack.jsx
  src/axios/AxiosInstance.js
  src/index.css
  src/pages/Mobile/MobileClip.jsx
  src/pages/Mobile/MobileLogin.jsx
  src/pages/User/Login.jsx
Labels: ✨Feature

#27 Feat: 게시물 상세보기 페이지 구현
  src/api/follow.js
  src/assets/svgs/bookmarked_icon.svg
  src/assets/svgs/toggle_icon.svg
  src/assets/svgs/unbookmarked_icon.svg
  src/components/post/PostLeftContainer.jsx
  src/components/post/PostRightContainer.jsx
  src/components/post/leftContainer/BookmarkButton.jsx
  src/components/post/leftContainer/FollowButton.jsx
  src/components/post/leftContainer/MapContainer.jsx
  src/components/post/leftContainer/TripInfo.jsx
  src/components/post/leftContainer/TripTitle.jsx
  src/components/post/rightContainer/DayCardComponent.jsx
  src/components/post/rightContainer/PlaceCardComponent.jsx
  src/components/post/rightContainer/PlaceContainer.jsx
  src/components/post/rightContainer/ReportModal.jsx
  src/components/post/rightContainer/ToggleButton.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostDetail.jsx
Labels: ✨Feature

#33 Refactor: 여행 계획 설정 페이지 코드 리팩토링
  src/api/tripInfo.js
  src/components/map/MyMap.jsx
  src/components/planTripPage/LeftContainer.jsx
  src/components/planTripPage/RightContainer.jsx
  src/components/planTripPage/leftContainer/TripLocationContentContainer.jsx
  src/components/planTripPage/rightContainer/AddPlanContainer.jsx
  src/components/planTripPage/rightContainer/AddPlanMapContainer.jsx
  src/components/planTripPage/rightContainer/EditPlanMapContainer.jsx
  src/pages/Plan/Plan.jsx
Labels: 🔨 Refactor

#35 Feat: addPlanMapContainer 코드 수정
  src/components/planTripPage/LeftContainer.jsx
  src/components/planTripPage/rightContainer/AddPlanMapContainer.jsx
Labels: ✨Feature

#36 Feat: EditPlanMapContainer 기능 수정
  src/components/planTripPage/rightContainer/EditPlanMapContainer.jsx
Labels: ✨Feature

#37 Feat: 여행 계획 설정 페이지 - 완료 버튼 구현
  src/components/planTripPage/LeftContainer.jsx
  src/components/planTripPage/RightContainer.jsx
  src/components/planTripPage/rightContainer/AddPlanContainer.jsx
  src/components/planTripPage/rightContainer/CalendarInputWrapper.jsx
  src/components/planTripPage/rightContainer/RegistPartyContentsContainer.jsx
  src/pages/Plan/Plan.jsx
Labels: ✨Feature

#38 Feat: 목적지 검색하기에서 검색창 수정
  package-lock.json
  package.json
  src/components/planTripPage/rightContainer/AddPlanMapContainer.jsx
  src/components/planTripPage/rightContainer/EditPlanMapContainer.jsx
Labels: ✨Feature

#40 [Refactor] 모든 Post 불러오는 기능 client-server 연결
  src/api/allposts.js
  src/api/fileDetail.js
  src/api/tripDetail.js
  src/api/userDetail.js
  src/assets/images/default-profile-image.png
  src/assets/images/icons/party/couple.png
  src/assets/images/icons/party/friends.png
  src/assets/images/icons/party/solo.png
  src/components/iconUtils.js
  src/pages/Post/Post.jsx
Labels: ✨Feature, 🔨 Refactor

#42 Refactor: post upload api 호출 body 수정
  src/components/postMakePage/LowerContainer.jsx
  src/components/postMakePage/lowerContainer/TripDayContainer.jsx
  src/components/postMakePage/lowerContainer/TripPlaceContainer.jsx
  src/components/postMakePage/titleContainer/TripTitleContainer.jsx
  src/components/postMakePage/upperContainer/AddPlanMapMobileContainer.jsx
  src/components/postMakePage/upperContainer/UploadReadyContainer.jsx
  src/pages/Plan/MobilePostMake.jsx
Labels: 🔨 Refactor

#43 Refactor: trip info BE API로 받아온 data 변수명 변경
  src/pages/Plan/MobilePostMake.jsx
Labels: 🔨 Refactor

#48 Chore: vercel.json 파일 추가
  vercel.json
Labels: ⚙️ Chore
