Repository MTVS-Noblesse/Triplay-frontend, pull requests merged in 2024-08, with the labels that each got.

#2 [FEAT] 여행 계획 설정 시작 페이지 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/planTripStartPage/plantrip1.png
  src/assets/images/planTripStartPage/plantrip2.png
  src/assets/images/planTripStartPage/plantrip3.png
  src/assets/images/planTripStartPage/plantrip4.png
  src/assets/images/planTripStartPage/plantrip5.png
  src/pages/PlanTripStartPage.jsx
Labels: ✨Feature

#6 Feat: 여행 계획 설정 페이지 구현
  .gitignore
  package.json
  src/App.jsx
  src/axios/AxiosMethod.js
  src/components/locations.js
  src/components/map/MyMap.jsx
  src/components/map/SearchMap.jsx
  src/components/planTripPage/LeftContainer.jsx
  src/components/planTripPage/RightContainer.jsx
  src/components/planTripPage/leftContainer/TripLocationContentContainer.jsx
  src/components/planTripPage/rightContainer/AddPlanContainer.jsx
  src/components/planTripPage/rightContainer/AddPlanMapContainer.jsx
  src/components/planTripPage/rightContainer/CalendarInputWrapper.jsx
  src/components/planTripPage/rightContainer/EditPlanMapContainer.jsx
  src/components/planTripPage/rightContainer/RegistPartyContentsContainer.jsx
  src/main.jsx
  src/pages/PlanTripPage.jsx
  src/pages/PlanTripStartPage.jsx
Labels: ✨Feature

#11 Fix: import 안한 오류 수정
  src/App.jsx
Labels: 🐞Fix

#9 Feat: ClipStartPage
  src/App.jsx
  src/assets/images/clipStartPage/plusCircleButton.jpg
  src/pages/ClipStartPage.jsx
Labels: ✨Feature

#15 Refactor: ClipStartPage file structure moved, App.jsx import refactor
  src/App.jsx
  src/pages/Plan/ClipStartPage.jsx
Labels: 🔨 Refactor
