Repository MTVS-Noblesse/Triplay-frontend, pull requests merged in 2024-11, with the labels that each got.

#54 Feature: 관리자 로그인 페이지 구현 완료
  package-lock.json
  package.json
  src/App.jsx
  src/assets/svgs/branding.svg
  src/assets/svgs/header_logo.svg
  src/components/admin/AdminRoute.jsx
  src/layout/AdminHeader.jsx
  src/pages/Admin/AdminLogin.jsx
Labels: ✨Feature

#56 Feature: 관리자 메인(대시보드) 페이지 구현 완료
  src/pages/Admin/Admin.jsx
Labels: ✨Feature

#69 Feat: Clip 저장 페이지 구현 및 BE 연동
  src/App.jsx
  src/components/clipMakePage/upperContainer/ClipExtraInfoRegistComponent.jsx
  src/components/clipMakePage/upperContainer/ClipImageUploadComponent.jsx
  src/components/clipMakePage/upperContainer/ClipPreviewComponent.jsx
  src/components/clipMakePage/upperContainer/LoadingComponent.jsx
  src/components/postMakePage/UpperContainer.jsx
  src/components/postMakePage/lowerContainer/TripPlaceContainer.jsx
  src/components/postMakePage/titleContainer/TripTitleContainer.jsx
  src/components/postMakePage/upperContainer/UploadReadyContainer.jsx
  src/pages/Plan/MobileClipMake.jsx
  src/pages/Plan/MobilePostMake.jsx
Labels: ✨Feature

#70 Feat: 여행 계획 설정 페이지 에러 해결
  src/App.jsx
  src/components/map/MyMap.jsx
  src/components/planTripPage/LeftContainer.jsx
Labels: ✨Feature

#76 feat: 웹 페이지 Clip 둘러보기 기능 구현
  src/App.jsx
  src/components/post/PostRightContainer.jsx
  src/layout/Header.jsx
  src/pages/Clip/Clip.jsx
  src/pages/Clip/ClipDetail.jsx
  src/pages/Plan/MobileClipMake.jsx
Labels: ✨Feature

#79 [Refactor] 여행 계획 페이지 css 수정
  src/components/planTripPage/LeftContainer.jsx
  src/components/planTripPage/RightContainer.jsx
  src/components/planTripPage/leftContainer/TripLocationContentContainer.jsx
  src/components/planTripPage/rightContainer/AddPlanContainer.jsx
  src/components/planTripPage/rightContainer/CalendarInputWrapper.jsx
  src/components/planTripPage/rightContainer/RegistPartyContentsContainer.jsx
  src/pages/Plan/Plan.jsx
Labels: 🔨 Refactor

#77 Feat: Mypage view 구현
  src/api/myPage.js
  src/api/preferences.js
  src/assets/images/icons/preference/activity.png
  src/assets/images/icons/preference/art.png
  src/assets/images/icons/preference/gourmet.png
  src/assets/images/icons/preference/shopping.png
  src/assets/images/icons/preference/sns.png
  src/components/iconUtils.js
  src/components/mypageModify/PreferencesSection.jsx
  src/components/mypageModify/UserInfoSection.jsx
  src/layout/Header.jsx
  src/pages/User/MyPage.jsx
Labels: ✨Feature, 🔨 Refactor

#86 Feat: 로그 수집 및 그라파나 대시보드 페이지 구현
  src/App.jsx
  src/pages/Admin/Admin.jsx
  src/pages/Admin/AdminGrafanaManage.jsx
  src/pages/Admin/AdminLogManage.jsx
  src/pages/Admin/AdminManage.jsx
  src/pages/Admin/AdminManageNotice.jsx
  src/pages/Admin/AdminManageUser.jsx
Labels: ✨Feature

#88 [Refactor] Post 관련 뷰 개선
  src/api/comment.js
  src/api/user.js
  src/api/userDetail.js
  src/assets/svgs/toggle_icon.svg
  src/components/comment/CommentSection.jsx
  src/components/mypageModify/UserInfoSection.jsx
  src/components/post/PostLeftContainer.jsx
  src/components/post/PostRightContainer.jsx
  src/components/post/leftContainer/FollowButton.jsx
  src/components/post/leftContainer/ReportModal.jsx
  src/components/post/leftContainer/TripInfo.jsx
  src/components/post/leftContainer/TripTitle.jsx
  src/components/post/rightContainer/DayCardComponent.jsx
  src/components/post/rightContainer/PlaceCardComponent.jsx
  src/hooks/get-current-user.js
  src/index.css
  src/layout/Header.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/PostDetail.jsx
Labels: 🔨 Refactor

#89 [Refactor] 취향 api 연결
  src/api/preferences.js
  src/components/mypageModify/PreferencesSection.jsx
  src/pages/Post/Post.jsx
Labels: 🔨 Refactor

#90 [Feat] 여행 계획 조회 기능 추가
  src/App.jsx
  src/api/myPage.js
  src/components/mypage/TripCard.jsx
  src/components/plan/PlanLeftContainer.jsx
  src/components/plan/PlanRightContainer.jsx
  src/pages/Plan/PlanDetail.jsx
  src/pages/User/MyPage.jsx
Labels: ✨Feature, 🔨 Refactor

#91 [Feat] 여행 계획 편집 모드 추가
  package-lock.json
  package.json
  src/api/tripDetail.js
  src/components/plan/PlanLeftContainer.jsx
  src/components/planTripPage/LeftContainer.jsx
  src/components/planTripPage/RightContainer.jsx
  src/components/planTripPage/rightContainer/AddPlanContainer.jsx
  src/hooks/get-current-user.js
  src/pages/Plan/PlanDetail.jsx
  src/pages/Plan/PlanEdit.jsx
  src/pages/User/MyPage.jsx
Labels: ✨Feature, 🔨 Refactor

#92 refactor: 포스트 정보 가져오는 화면 수정
  src/api/myPage.js
  src/components/mypage/PostCard.jsx
  src/components/planTripPage/rightContainer/RegistPartyContentsContainer.jsx
  src/pages/User/MyPage.jsx
Labels: 🔨 Refactor

#93 refactor: css 1차 수정
  src/assets/images/planTripStartPage/plantrip1.png
  src/layout/Header.jsx
  src/pages/Main.jsx
Labels: 🔨 Refactor
